// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Exec$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Exec";
  readonly sourceName: "contracts/utils/Exec.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea264697066735822122093d1d404ecd0ba670b4e6c8a00c12d5407ed6149cb2b06ebd773e51035101ebb64736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea264697066735822122093d1d404ecd0ba670b4e6c8a00c12d5407ed6149cb2b06ebd773e51035101ebb64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/utils/Exec.sol";
  readonly buildInfoId: "solc-0_8_28-e645c8cf890fd1001194059a5c02f623c4285a2e";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Exec"]: Exec$Type;
    ["contracts/utils/Exec.sol:Exec"]: Exec$Type;
  }
}